language: ruby
cache: bundler
cache: bundler
sudo: false

before_install: |-
  wget -O vault.zip -q https://releases.hashicorp.com/vault/0.5.2/vault_0.5.2_linux_amd64.zip
  unzip vault.zip
  mkdir ~/bin
  mv vault ~/bin
  export PATH="~/bin:$PATH"

branches:
  only:
    - master

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
